server:
  port: ${PORT:8762} # Indicare the default PORT where this service will be started
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # telling the server not to register himself in the 
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
